/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gitflow.test;

public class App {
    public String getGreeting() {
        return "This is a change for git purposes!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
